name: Update Changelog
on:
  push:
    branches:
      - main
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: PR
      - name: update-changelog
        if: steps.PR.outputs.number != ''
        run: |
          MAJOR_VERSION=$(ls | grep CHANGELOG |  cut -d'-' -f 2 | cut -f 1 -d '.' |  grep v | sort -V -r | head -n 1)
          if [ -z "$MAJOR_VERSION" ]; then
            MAJOR_VERSION=0
          fi
          MAJOR_VERSION=${MAJOR_VERSION#"v"}
          MAJOR_VERSION=$((MAJOR_VERSION+1))
          docker run --rm -v $(pwd):/src -w /src githubchangeloggenerator/github-changelog-generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }} --no-issues --no-compare-link --since-tag $MAJOR_VERSION.0.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog